name: Anurag Ramdasan
description:
meta_description: "on programming and all things code."

markdown: redcarpet
pygments: true
logo: false

permalink: /weblog/:title

# Details for the RSS feed generator
url:            'http://anuragramdasan.com'
author:         'Anurag Ramdasan'

sitemap: 
    include_post: 
        - "/archive.html"
