name: Anurag Ramdasan
description:
meta_description: "on programming and all things code."

markdown: redcarpet
pygments: true
logo: false

# Details for the RSS feed generator
author:         'Anurag Ramdasan'
